spring.application.name=account-service
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/orm_learn?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vishnu@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true